# Generated by Django 3.1.7 on 2021-04-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentsMethod',
            new_name='paymentMethod',
        ),
    ]
