# Generated by Django 3.1.7 on 2021-09-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210402_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/image.jpg', null=True, upload_to=''),
        ),
    ]
